export const LOGIN = "LOGIN"
export const TOKEN = "TOKEN"
export const GET_USERS = "GET_USERS"
export const GET_VENDORS = "GET_VENDORS"
export const GET_COUNT_DATA = "GET_COUNT_DATA"
export const GET_PRODUCTS = "GET_PRODUCTS"